---
# Github action template to notify a MS Teams channel on failure - PLT-450
name: NotifyOnFailure
description: "GitHub Action to notify on failure"

inputs:
  github-workflow:
    description: "The name of the GitHub workflow."
    required: true
  msteams-channel-webhook:
    description: "The webhook URI for the MS Teams channel."
    required: true
  github-repository:
    description: "The name of the GitHub repository."
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify dedicated teams channel
      uses: ClimatePartner/ms-teams-card-action@main
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.msteams-channel-webhook }}
        notification-summary: "${{ inputs.github-repository }} failed Pipeline: ${{ inputs.github-workflow }}"
        notification-color: 'eb0101'
        timezone: Europe/Berlin