---
# Github action template to notify a MS Teams channel on failure - PLT-450
name: NotifyOnFailure

inputs:
  github-workflow:
    required: true
  msteams-channel-webhook:
    required: true
  github-repository:
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify dedicated teams channel
      uses: dragos-cojocari/ms-teams-notification@v1.0.0
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.msteams-channel-webhook }}
        notification-summary: "${{ inputs.github-repository }} failed Pipeline: ${{ inputs.github-workflow }}"
        notification-color: 'eb0101'
        timezone: Europe/Berlin