name: 'Pull Request'

on:
  pull_request:

jobs:
  test:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - run: pnpm all
        name: Test and compile
