name: "Pull Request"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.payload.pull_request.head.ref }}

    - run: yarn install --frozen-lockfile
      name: Install dependencies

    - run: yarn all
      name: Test and compile

    - name: Commit
      run: |
        git status
        git branch
        # git config --global user.name "GitHub Actions"
        # git add dist/
        # git commit -m "chore: Update dist" || echo "No changes to commit"
        # git push origin HEAD:master

