name: "Pull Request"

on:
  pull_request:

jobs:
  test:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile
        name: Install dependencies

      - run: yarn all
        name: Test and compile
